name: feven
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^7.6.0

  # Bloc for state management
  flutter_bloc: ^8.1.3

  # Value equality
  equatable: ^2.0.5

  # Functional programming
  dartz: ^0.10.1

  # Connectivity (new package)
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1

  # HTTP client
  http: ^1.2.2

  # Local cache
  shared_preferences: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/men_shoe.png
